# Exmpla configuration for chatvoice
[default.console]
name="🤖"
logging_json="False"
logging_level="INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
logging_file="logs/chatvoice.log"

[colors]
name="Magical color"
