"""add conversation log and turn tables

Revision ID: 71eec961a664
Revises: a67d1534c444
Create Date: 2026-08-10 23:25:55.809054

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71eec961a664"
down_revision: Union[str, Sequence[str], None] = "a67d1534c444"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("script_name", sa.String(length=500), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_conversation_log_project_id"),
        "conversation_log",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_log_session_id"),
        "conversation_log",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_log_user_id"),
        "conversation_log",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "conversation_turn",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_log_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_log_id"], ["conversation_log.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_turn_conversation_log_id"),
        "conversation_turn",
        ["conversation_log_id"],
        unique=False,
    )
    # VARCHAR widened to fit the new "observer" role value (native_enum=False
    # stores UserRole as a plain VARCHAR sized to the longest member).
    # batch_alter_table: SQLite has no ALTER COLUMN ... TYPE; this recreates
    # the table under the hood there, and is a plain ALTER on other backends.
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=6),
            type_=sa.Enum(
                "user", "editor", "observer", "admin", name="userrole", native_enum=False
            ),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum(
                "user", "editor", "observer", "admin", name="userrole", native_enum=False
            ),
            type_=sa.VARCHAR(length=6),
            existing_nullable=False,
        )
    op.drop_index(
        op.f("ix_conversation_turn_conversation_log_id"), table_name="conversation_turn"
    )
    op.drop_table("conversation_turn")
    op.drop_index(op.f("ix_conversation_log_user_id"), table_name="conversation_log")
    op.drop_index(op.f("ix_conversation_log_session_id"), table_name="conversation_log")
    op.drop_index(op.f("ix_conversation_log_project_id"), table_name="conversation_log")
    op.drop_table("conversation_log")
    # ### end Alembic commands ###
